language: java

jdk:
  - openjdk11
  - oraclejdk8

services: mongodb

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "aidanwhiteley-github"

cache:
  directories:
  - $HOME/.m2

script:
  # other script steps might be done before running the actual analysis
  - git fetch --unshallow
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
