# Run the Docker containers for the
# a) books api microservice - https://github.com/aidanwhiteley/books
# b) the books web tier SPA - https://github.com/aidanwhiteley/books-web

version: '2'

services:

  webtier:
    container_name: books-web-container
    image: aidanwhiteley/books-web
    restart: always
    ports:
      - 80:80
    depends_on:
      - javatier

  javatier:
    container_name: books-spring-boot-container
    image: aidanwhiteley/books-spring-boot
    restart: always
    expose:
      - "8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=mongo-java-server-no-auth"