security:
  basic:
    enabled: false
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/books-dev?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000

books:
  reload:
    development:
      data: true    # Whether the contents of the /src/main/resources/sample_data will be reloaded into the database at application startup. Deletes all existing data!!!

  users:
    default:
      admin:
        email: thecloudybookclub@gmail.com  # The remote email address for the user that will be automatically made an admin on first logon