security:
  basic:
    enabled: false
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/books-dev?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000