

spring:

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstest?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000


logging:
  level:
    root:INFO
    org.springframework.test:INFO


security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me


books:
  client:
    allowedCorsOrigin: http://localhost:9000

