spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/books-test?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000

  devtools:
    livereload:
      enabled: false  # off as we already have live reload in the web tier project

logging:
  level:
    root:INFO
    org.springframework.test.:INFO
    com.aidanwhiteley.books.controller.LogonController:DEBUG
    org.springframework.web.client.RestTemplate:DEBUG
    com.aidanwhiteley.books.repository.debugging.:INFO

security:
    oauth2:
        client:
            clientId: NotInSCM
            clientSecret: NotInSCM
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile,email
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false

books:
  client:
    allowedCorsOrigin: http://localhost:9000
    postLogonUrl: http://localhost:9000/#/?l=1

  google:
    books:
      api:
        searchUrl: https://www.googleapis.com/books/v1/volumes?q=
        getByIdUrl: https://www.googleapis.com/books/v1/volumes/
        connect:
          timeout: 2000
        read:
          timeout: 5000

