spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/books-test?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000

  devtools:
    livereload:
      enabled: false  # off as we already have live reload in the web tier project

logging:
  level:
    root:INFO
    org.springframework.test.:INFO
    com.aidanwhiteley.books.controller.LogonController:DEBUG
    org.springframework.web.client.RestTemplate:DEBUG
    com.aidanwhiteley.books.repository.debugging.:INFO

google:
  client:
    clientId: NotInSCM
    clientSecret: NotInSCM
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile,email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false

facebook:
  client:
    clientId: NotInSCM
    clientSecret: NotInSCM
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=name, first_name, last_name, link, picture, email

books:
  client:
    allowedCorsOrigin: http://localhost:9000
    postLogonUrl: http://localhost:9000/

  google:
    books:
      api:
        searchUrl: https://www.googleapis.com/books/v1/volumes?maxResults=30&q=
        getByIdUrl: https://www.googleapis.com/books/v1/volumes/
        countryCode: country=GB
        connect:
          timeout: 2000
        read:
          timeout: 3000

  reload:
    development:
      data: false  # Whether the contents of the /src/main/resources/sample_data will be reloaded into the database at application startup. Deletes all existing data!!!

  users:
    default:
      admin:
        email:   # The remote email address for a user that will be automatically made an admin on first logon.
      page:
        size: 5

